version: '3'

services:
  db:
    restart: always
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./src/main/java/com.RestaurantManagementSystem/utils/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
